name: Hugo Build Check

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build-check:
    name: Validate Hugo Build
    runs-on: ubuntu-latest
    env:
      HUGO_VERSION: 0.146.0
      HUGO_ENVIRONMENT: production
      TZ: America/Los_Angeles

    steps:
      - name: Install Hugo
        run: |
          wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.deb
          sudo dpkg -i ${{ runner.temp }}/hugo.deb

      - name: Install Dart Sass
        run: sudo snap install dart-sass

      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Build Hugo Site
        run: hugo --gc --minify